# Generated by Django 4.0.6 on 2022-07-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_Number', models.CharField(max_length=15, null=True, unique=True)),
                ('registration_date', models.DateField()),
                ('First_Name', models.CharField(max_length=14, null=True)),
                ('Last_Name', models.CharField(max_length=13, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=17, null=True)),
            ],
        ),
    ]
