# Generated by Django 4.0.6 on 2022-07-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='registration_date',
            new_name='Registration_date',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_Number',
            new_name='patient_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='First_Name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Last_Name',
        ),
        migrations.AddField(
            model_name='patient',
            name='First_name',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
